extern const GeoLayout pokey_body_part_geo[];
extern Lights1 pokey_f3dlite_material_010_lights;
extern Lights1 pokey_f3dlite_material_011_lights;
extern Lights1 pokey_f3dlite_material_012_lights;
extern Lights1 pokey_f3dlite_material_009_lights;
extern u8 pokey_VFBRG_rgba16[];
extern u8 pokey_K_Sflower_orange_rgba16[];
extern Vtx pokey_000_displaylist_mesh_layer_1_vtx_0[107];
extern Gfx pokey_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx pokey_000_displaylist_mesh_layer_1_vtx_1[28];
extern Gfx pokey_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx pokey_000_displaylist_mesh_layer_1_vtx_2[27];
extern Gfx pokey_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx pokey_000_displaylist_mesh_layer_5_vtx_0[52];
extern Gfx pokey_000_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_pokey_f3dlite_material_010[];
extern Gfx mat_pokey_f3dlite_material_011[];
extern Gfx mat_pokey_f3dlite_material_012[];
extern Gfx mat_pokey_f3dlite_material_009[];
extern Gfx mat_revert_pokey_f3dlite_material_009[];
extern Gfx pokey_000_displaylist_mesh_layer_1[];
extern Gfx pokey_000_displaylist_mesh_layer_5[];
extern Gfx pokey_material_revert_render_settings[];
extern const GeoLayout pokey_body_part_geo[];
extern Vtx pokey_body_000_displaylist_mesh_layer_1_vtx_0[223];
extern Gfx pokey_body_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx pokey_body_000_displaylist_mesh_layer_1_vtx_1[72];
extern Gfx pokey_body_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_pokey_body_f3dlite_material_010[];
extern Gfx mat_pokey_body_f3dlite_material_011[];
extern Gfx pokey_body_000_displaylist_mesh_layer_1[];
extern Gfx pokey_body_material_revert_render_settings[];

