extern const GeoLayout transparent_star_geo[];
extern Lights1 transparent_star_transparent_star_body_001_lights;
extern Vtx transparent_star_transparent_star_mesh_layer_5_vtx_0[12];
extern Gfx transparent_star_transparent_star_mesh_layer_5_tri_0[];
extern Gfx mat_transparent_star_transparent_star_body_001[];
extern Gfx mat_revert_transparent_star_transparent_star_body_001[];
extern Gfx transparent_star_transparent_star_mesh_layer_5[];
extern Gfx transparent_star_material_revert_render_settings[];
