extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_009_lights;
extern Lights1 bob_dl_f3dlite_material_010_lights;
extern Lights1 bob_dl_f3dlite_material_005_lights;
extern Lights1 bob_dl_f3dlite_material_007_lights;
extern Lights1 bob_dl_f3dlite_material_011_lights;
extern Lights1 bob_dl_f3dlite_material_006_lights;
extern u8 bob_dl_image4_rgba16[];
extern u8 bob_dl_image3_rgba16[];
extern u8 bob_dl_E009C10_ia16[];
extern u8 bob_dl_image2_rgba16[];
extern u8 bob_dl_image1_rgba16[];
extern u8 bob_dl_carpet_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[213];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[8];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[238];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[48];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[240];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx bob_dl_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_009[];
extern Gfx mat_bob_dl_f3dlite_material_010[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_bob_dl_f3dlite_material_011[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_revert_bob_dl_f3dlite_material_006[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_4[];
extern Gfx bob_dl_material_revert_render_settings[];
