extern const GeoLayout boo_001_switch_opt1_switch_face_opt1[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt2[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt3[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt4[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt5[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt6[];
extern const GeoLayout boo_001_switch_opt1_switch_face_opt7[];
extern const GeoLayout boo_armature_002_switch_option_002[];
extern const GeoLayout boo_geo[];
extern Lights1 boo_f3dlite_material_006_lights;
extern Lights1 boo_f3dlite_material_008_lights;
extern Lights1 boo_f3dlite_material_007_lights;
extern Lights1 boo_f3dlite_material_004_lights;
extern Lights1 boo_f3dlite_material_002_lights;
extern Lights1 boo_f3dlite_material_003_lights;
extern Lights1 boo_face_1___eye_half_v3_002_lights;
extern Lights1 boo_face_2___eye_closed_v3_002_lights;
extern Lights1 boo_face_7___eye_X_v3_002_lights;
extern u8 boo_boo_mouth_rgba16_png_rgba16[];
extern u8 boo_boo_eyes_rgba16_png_rgba16[];
extern u8 boo_sad_rgba16[];
extern u8 boo_aaaa_rgba16[];
extern u8 boo_Mario_Eyes_Half_rgba16[];
extern u8 boo_Mario_Eyes_Closed_rgba16[];
extern u8 boo_Mario_Eyes_Dead_rgba16[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_0[6];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_1[62];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_2[6];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx boo_002_switch_option_head__no_cap__mesh_layer_1_vtx_0[12];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_tri_0[];
extern Vtx boo_002_switch_option_head__no_cap__mesh_layer_1_vtx_1[93];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_tri_1[];
extern Vtx boo_002_switch_option_head__no_cap__mesh_layer_1_vtx_2[7];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_tri_2[];
extern Gfx mat_boo_f3dlite_material_006[];
extern Gfx mat_boo_f3dlite_material_008[];
extern Gfx mat_boo_f3dlite_material_007[];
extern Gfx mat_boo_f3dlite_material_004[];
extern Gfx mat_boo_f3dlite_material_002[];
extern Gfx mat_boo_f3dlite_material_003[];
extern Gfx mat_boo_face_1___eye_half_v3_002[];
extern Gfx mat_boo_face_2___eye_closed_v3_002[];
extern Gfx mat_boo_face_7___eye_X_v3_002[];
extern Gfx boo_000_displaylist_mesh_layer_1[];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1[];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_1___eye_half_v3_002_0[];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_2___eye_closed_v3_002_1[];
extern Gfx boo_002_switch_option_head__no_cap__mesh_layer_1_mat_override_face_7___eye_X_v3_002_2[];
extern Gfx boo_material_revert_render_settings[];
